# Generated by Django 2.0.6 on 2018-07-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink_item',
        ),
    ]
