# Generated by Django 2.0.6 on 2018-07-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_delete_drink_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='None_item',
        ),
    ]
