# Generated by Django 2.0.6 on 2018-07-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_choice', models.CharField(choices=[('Alcohol', (('beers', 'Beers'), ('wines', 'Wines'), ('spirits', 'Spirits'), ('sin', 'Sin'))), ('None_Alcohol', (('pop', 'Pop'), ('mixers', 'Mixers'), ('cartons', 'Cartons'), ('water', 'Water'), ('cordial', 'Cordial'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('malted', 'Malted')))], default='Alcohol', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('thumb', models.ImageField(default='default.png', null=True, upload_to='')),
                ('body', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink_item',
        ),
        migrations.AddField(
            model_name='dcat',
            name='drink_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drinks.Ditem'),
        ),
    ]
